apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
imagePullSecrets:
- name: stackrox
---

kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: monitoring is the security constraint for the monitoring stack
  name: monitoring
  labels:
    app.kubernetes.io/name: stackrox
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
users:
- system:serviceaccount:stackrox:monitoring
volumes:
- '*'

