
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: central-htpasswd
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox

  annotations:
    "helm.sh/hook": "pre-install"

data:
  htpasswd: YWRtaW46JDJhJDA1JG8ybkFycS9mRnBKcXVLZUEzUy4zcmV6L0hsOVY3QThlT1pwYkh4cjRHWTVMRUlad3h3UTRPCg==


